export const GAME_CONFIG = {
  // Game mechanics
  NUMBER_OF_COMBINATIONS: 3,
  MAX_SPIN_LENGTH: 9,
  DELAY_SECONDS_AFTER_WINNING: 5,
  
  // Animation durations
  DOOR_OPEN_DURATION: 0.5,
  DOOR_CLOSE_DURATION: 0.5,
  HANDLE_ROTATION_DURATION: 0.5,
  HANDLE_SPIN_DURATION: 1,
  GLITTER_FADE_DURATION: 2,
  GLITTER_PAUSE_DURATION: 0.1,
  HANDLE_FADE_DURATION: 0.3,
  
  // UI positioning
  TIMER_PADDING: 20,
  DOOR_SCALE_FACTOR: 0.60,
  DOOR_POSITION_X_FACTOR: 1.95,
  DOOR_POSITION_Y_FACTOR: 2.1,
  HANDLE_POSITION_X_FACTOR: 0.457,
  HANDLE_POSITION_Y_FACTOR: 0.5,
  GLITTER_POSITION_X_FACTOR: 3,
  GLITTER_POSITION_Y_FACTOR: 4.5,
  
  // Visual effects
  GLITTER_SCALE: 0.8,
  HANDLE_ROTATION_AMOUNT: Math.PI / 3,
  HANDLE_SPIN_ROTATIONS: 4,
  SHADOW_ALPHA: 0.5,
  
  // Timer
  TIMER_UPDATE_INTERVAL: 100,
  
  // Colors
  BACKGROUND_COLOR: 0x23272a,
  TIMER_TEXT_COLOR: "white",
  TIMER_FONT_SIZE: 24,
  TIMER_FONT_FAMILY: "Arial"
} as const;

export enum Direction {
  CLOCKWISE = "clockwise",
  COUNTERCLOCKWISE = "counterclockwise"
}

export enum GameStatus {
  NORMAL = "normal",
  WIN = "win",
  FAILURE = "failure"
} 